---

- name: Install ZSH with completion and syntax
  pacman:
    name:
      - zsh
      - zsh-autosuggestions
      - zsh-completions
      - zsh-theme-powerlevel10k
    state: present

- name: Clone oh-my-zsh
  command: 'git clone https://github.com/ohmyzsh/ohmyzsh.git .oh-my-zsh'
  args:
    chdir: '~{{ user.name }}'
    creates: '~{{ user.name }}/.oh-my-zsh'

- name: Configures oh-my-zsh and changes default shell
  command: 'cp ~{{ user.name }}/.oh-my-zsh/templates/zshrc.zsh-template ~/.zshrc'

- name: Ensure the cache folder with oh-my-zsh subfolder is present
  file:
    path: /home/{{ user.name }}/.cache/oh-my-zsh
    owner: "{{ user.name }}"
    group: "{{ user.group }}"
    state: directory
    mode: 0755

- name: Ensure the last working dir file for oh-my-zsh is present
  file:
    path: /home/{{ user.name }}/.cache/oh-my-zsh/last-working-dir
    owner: "{{ user.name }}"
    group: "{{ user.group }}"
    state: touch

- name: Update user shell to ZSH
  user:
    name: "{{ user.name }}"
    shell: /bin/zsh
  become: true
