---

- name: Install bluetooth tools
  pacman:
    name: 
      - blueman
      - bluez
      - bluez-utils
    state: present

- name: Enable bluetooth service
  service: name=bluetooth state=started enabled=true
