---

- name: Install dependencies
  pacman:
    name:
      - lightdm
      - lightdm-gtk-greeter
      - lightdm-slick-greeter
    state: present

- name: Write LightDM configuration
  template:
    src: lightdm.conf.j2
    dest: '/etc/lightdm/lightdm.conf'
    owner: root
    group: root
    mode: 'u=rw,go=r'
  register: lightdm_config

- name: Enable lightdm service
  service:
    name: lightdm
    enabled: yes
