---

- name: Install network tools
  community.general.pacman:
    name:
      - ethtool
      - wpa_supplicant
      - netctl
      - dhcpcd
      - nmap
      - net-tools
      - networkmanager
      - network-manager-applet
      - networkmanager-openconnect
      - networkmanager-openvpn
    state: present
  register: task_result
  until: task_result is success
  retries: 10
  delay: 2

- name: Enable DHCP service
  ansible.builtin.service: name=dhcpcd state=started enabled=true

- name: Enable NetworkManager service
  ansible.builtin.service:
    name: NetworkManager
    state: started
    enabled: true
