--- 

- name: Install Alacritty terminal emulator
  pacman:
    name: alacritty
    state: present
  register: task_result
  until: task_result is success
  retries: 10
  delay: 2

- name: Install tmux terminal multiplexer
  pacman:
    name: tmux
    state: present
  register: task_result
  until: task_result is success
  retries: 10
  delay: 2
