---

- name: Ensure the 'aur_builder' user exists
  user:
    name: aur_builder
    create_home: true
    group: wheel

- name: Ensure the 'aur_builder' user can run 'sudo pacman' without a password
  lineinfile:
    path: /etc/sudoers.d/11-install-aur_builder
    line: 'aur_builder ALL=(ALL) NOPASSWD: /usr/bin/pacman'
    create: true
    validate: 'visudo -cf %s'

- name: Ensure multilib repository is enabled
  ini_file:
    path: /etc/pacman.conf
    create: false
    section: multilib
    option: Include
    value: /etc/pacman.d/mirrorlist

- name: Ensure the system package definition is up to date
  pacman:
    update_cache: true
    upgrade: false

- name: Check if paru AUR helper is available
  stat:
    path: /usr/bin/paru
  register: paru_stat_result

- name: Ensure packages for building AUR packages are installed
  pacman:
    state: present
    name:
      - fakeroot
      - git
      - gnupg

- name: Clone paru AUR helper repository
  become_user: aur_builder
  git:
    repo: https://aur.archlinux.org/paru.git
    version: master
    dest: /tmp/paru
  when: not paru_stat_result.stat.exists

- name: Install paru AUR helper package
  become_user: aur_builder
  command:
    chdir: /tmp/paru
    cmd: makepkg -si --noconfirm
  when: not paru_stat_result.stat.exists

- name: Ensure paru AUR helper package is up to date
  become_user: aur_builder
  kewlfft.aur.aur:
    name:
      - yay
  when: paru_stat_result.stat.exists

- name: Ensure the desired packages are installed
  pacman:
    state: present
    name: '{{ base_packages }}'

- name: Ensure the desired AUR packages are installed
  become_user: aur_builder
  kewlfft.aur.aur:
    name:
      - inxi

- name: Ensure bluetooth packages are installed
  pacman:
    state: present
    name:
      - blueman
      - bluez-utils
