---

- name: Ensure group user.group exists
  group: name={{ user.group }} state=present
  when: user.name is defined

- name: Ensure the user user.name exists
  user:
    name: "{{ user.name }}"
    shell: "{{ user.shell }}"
    groups:
      - "{{ user.group }}"
      - wheel
      - network
      - lock
      - uucp
    append: true
    system: false
    createhome: true
    home: /home/{{ user.name }}
  when: user.name is defined
