---

- name: Install packages
  pacman:
    state: present
    name: '{{ looks_packages }}'

- name: Install AUR packages
  become_user: aur_builder
  kewlfft.aur.aur:
    name: '{{ looks_aur_packages }}'
